### ISSUE TITLE
exac import error

### ISSUE THREAD

**Issue by ramaniak** [ChristofferFlensburg/superFreq#24] opened 2017-10-31 15:32 UTC
Hello Christoffer,
I upgraded to the latest version and tried running some of my samples and get the following error. 
I manually downloaded the exac.Rdata (http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/dbSNP/exac.Rdata) to the working directory and re-ran and still get the same error. 

Importing exac allele frequencies from superFreqDbSNP/exac.Rdata...done. Match against variants...Error in .Method(..., na.last = na.last, decreasing = decreasing, method = method) : 
  argument 1 is not a vector
Calls: superFreq ... order -> standardGeneric -> eval -> eval -> eval -> .Method
In addition: Warning messages:
1: In checkSystem(vepCall) :
  'samtools --version' failed. This is likely to cause problems downstream in variant calling.
2: In checkSystem(vepCall) :
  'samtools --version' failed. This is likely to cause problems downstream in variant calling.

**Comment by ChristofferFlensburg** [comment] 2017-11-01 00:57
Hey Arun!

There were issues with the exac file at a certain point, but I think that was fixed a while ago. Is this hg19? To be sure that you have the right file (there is one for hg19 and one for hg38, and there may be old version online as well), you can delete (or rename) the superFreqDbSNP directory, and it'll automatically download the right one.

But I wonder if it's not the samtools warning that's the problem here. Are you running an old (0.X) samtools version on the system? If so, it is probably a good idea to update to 1.X (1.3+ is tested, not sure about 1.0 to 1.2 but think it should work) and rerun with

``` R
forceRedo$forceRedoVariants = TRUE
forceRedo$forceRedoNormalVariants = TRUE
```

**Comment by ramaniak** [comment] 2017-11-01 01:45
Hello Christoffer,

I did see the previous issue (now closed) that mentioned the exac problem.
the latest version is superFreq_0.9.22, correct? This was installed in our
cluster last week and I see there have been some commits yesterday, would
they matter?

Exac was for hg19 and to be safe, I deleted the existing files and re-ran.
it did download the files again. I also have 1.x of samtools and checked

>samtools --version
samtools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.


I still get the same error unfortunately :(

Importing exac allele frequencies from superFreqDbSNP/exac.Rdata...done.
Match against variants...Error in .Method(..., na.last = na.last,
decreasing = decreasing, method = method) :
  argument 1 is not a vector
In addition: Warning message:
In checkSystem(vepCall) :
  'samtools --version' failed. This is likely to cause problems downstream
in variant calling.

**Comment by ChristofferFlensburg** [comment] 2017-11-01 02:42
Hmm, then I'm not sure. 0.9.22 is indeed the latest and should be fine for this. The commits last days were changes to the manual and that kind of things. Shouldn't affect this.

There error is from matching up the exac data with the variants, but it's not clear to me at this point if this a problem with the exac data or with the variants. Actually... It's a long shot, but another user (Gil) had the exact same error message, and as I udnerstand it was caused by very deeply sequenced (~1000+ read depth) exomes. Apparently there is an issue with piping the samtools mpileup output directly into R when the lines are too long. Do you think this could be the case for you?

Otherwise, can you send me the log file and I'll look closer? It's in the R directory (subdirectory of the individual if running split mode), runtimeTracking.log. It contains your meta data as you entered it, so don't post it here if you're not comfortable with that. You can email otherwise. There is no identifying genomic data from the samples though.

**Comment by ChristofferFlensburg** [comment] 2017-11-02 06:46
So I think we (well, you) tracked this down to an issue with the input VCF? We are still not exactly sure why the input VCF didn't produce expected results, but as the problem doesn't seem to be related to exac, I'll close this issue for now. Feel free to open a new one with the VCF problem if it persists.

**Closed** 2017-11-02 06:46 UTC
