### ISSUE TITLE
Could not parse the "#CHROM.." line

### ISSUE THREAD

**Issue by maheshworpaudel5001** [ChristofferFlensburg/superFreq#100] opened 2023-03-20 13:05 UTC
Running superFreq in cluster environment with R/4.2.2: produced this error:
Mutaional signatures of somatic mutations...by sample..Creating directory /Users/mxp140/Desktop/superfreq_analysis/plots/brmet018/mutationalPatterns 
[E::bcf_hdr_parse_sample_line] Could not parse the "#CHROM.." line, either FORMAT is missing or spaces are present instead of tabs:
	#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	COVERAGE	VARIANTREADS	VAF

Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `h()`:
! error in evaluating the argument 'x' in selecting a method for function 'granges': error in evaluating the argument 'x' in selecting a method for function 'seqinfo': no 'header' line "#CHROM POS ID..."?
Run `rlang::last_trace()` to see where the error occurred.
Warning messages:
1: In system("awk '/MemFree/ {print $2}' /proc/meminfo", intern = TRUE) :
  running command 'awk '/MemFree/ {print $2}' /proc/meminfo' had status 2
2: In vafScatter(q1[use, ], q2[use, ], genome = genome, maxVariants = maxVariants/10,  :
  There are a total of 19396 variants to VAF scatter plot. Im subsampling to 10000 non-somatic variants to speed things up.

**Comment by ChristofferFlensburg** [comment] 2023-03-20 22:16
Hi, I've had this problem reported elsewhere. I think I know what it is, due to a change in the input requirements of MutationalPatterns in the most recent version. I'll try to reproduce and hopefully fix it relatively soon.

**Comment by maheshworpaudel5001** [comment] 2023-03-20 23:20
I was running version 1.4.4. I tried version 1.3.2 and it produced the same error. How much does it affect the number of output results (excel files and plots)? With this error, are other files credible to be used for post analysis?
Anyway, I have attached the tree that is generated by the run.
[files.txt](https://github.com/ChristofferFlensburg/superFreq/files/11023798/files.txt)

**Comment by ChristofferFlensburg** [comment] 2023-03-20 23:32
Yeah all current version of superFreq will have this conflict with the latest version of MutationalPatterns (or a dependency like GRanges). I'll need to update superFreq to work with the latest versions of MutationalPatters. Signatures are done at the very end, so I think you got all of the output otherwise, apart from the signature things of course.

**Comment by maheshworpaudel5001** [comment] 2023-03-28 16:25
I confirm that running superFreq-v1.4.4 on R-v4.1.0 did not complain about this error and ran successfully.

**Comment by ChristofferFlensburg** [comment] 2023-03-29 03:34
I pushed a fix for this just now. SueprFreq 1.4.5 hopefully should work on R 4.2.3.

**Closed** 2023-03-31 18:51 UTC
